---
abstract: 'Easy to use, flexible, parsable logs.'
author:
  - 'Mark Swayne <daotoad@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Lager
requires:
  Carp: 0
  Data::Abridge: 0
  Data::Dumper: 0
  Exporter: 0
  Hash::Util: 0
  IO::File: 0
  Scalar::Util: 0
  Sys::Syslog: 0
  constant: 0
  overload: 0
version: 0.02
