---
abstract: 'Easy to use, flexible, parsable logs.'
author:
  - 'Mark Swayne <daotoad@cpan.org>'
build_requires:
  File::Temp: 0
  JSON: 0
  Test::More: 0
  base: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300000, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Lager
requires:
  Carp: 0
  Config: 0
  Data::Abridge: 0
  Data::Dumper: 0
  Exporter: 0
  Hash::Util: 0
  IO::File: 0
  IO::Handle: 0
  JSON::XS: 0
  Scalar::Util: 0
  Sys::Hostname: 0
  Sys::Syslog: 0
  Time::HiRes: 0
  constant: 0
  overload: 0
  strict: 0
  warnings: 0
version: 0.04.05
